2021-09-16 16:08:48,434     INFO         server_log_config.py     Важная? информация
2021-09-16 16:08:48,435     DEBUG        server_log_config.py     Отладочное сообщение
2021-09-16 16:08:48,436     WARNING      server_log_config.py     Предупреждение!
2021-09-16 16:08:48,436     ERROR        server_log_config.py     Где-то ошибка!!
2021-09-16 16:08:48,436     CRITICAL     server_log_config.py     Где-то БОЛЬШАЯ ошибка!!!
2021-09-16 16:48:36,370     INFO         server.py                fЗапущен сервер с парамертами:  порт: 7777, адрес для приема подключений: ,Если адрес не указан, принимаются подключения со всех доступных адресов.
2021-09-16 16:48:47,164     INFO         server.py                Соедениние с клиентом ('127.0.0.1', 61264) установлено.
2021-09-16 16:48:47,168     DEBUG        server.py                Получено сообщение {'event': 'presence', 'time': 1631800127.164755, 'user': {'account_name': 'Guest'}}
2021-09-16 16:48:47,169     DEBUG        server.py                Обработка сообщения от клиента: {'event': 'presence', 'time': 1631800127.164755, 'user': {'account_name': 'Guest'}}
2021-09-16 16:48:47,169     DEBUG        server.py                Сформирован ответ клиенту {'response': 200}
2021-09-16 16:48:47,169     INFO         server.py                Соедениние с клиентом ('127.0.0.1', 61264) закрывается..
2021-09-16 16:51:49,787     INFO         server.py                Соедениние с клиентом ('127.0.0.1', 52074) установлено.
2021-09-16 16:51:49,787     DEBUG        server.py                Получено сообщение {'time': 1631800309.7879105, 'user': {'account_name': 'Guest'}}
2021-09-16 16:51:49,788     DEBUG        server.py                Обработка сообщения от клиента: {'time': 1631800309.7879105, 'user': {'account_name': 'Guest'}}
2021-09-16 16:51:49,788     DEBUG        server.py                Сформирован ответ клиенту {'response': 400, 'error': 'Bad Request'}
2021-09-16 16:51:49,788     INFO         server.py                Соедениние с клиентом ('127.0.0.1', 52074) закрывается..
