2021-09-14 03:17:32,804     INFO         client_log_config.py     Важная? информация
2021-09-14 03:17:32,804     DEBUG        client_log_config.py     Houston, we have a %s, thorny problem, exc_info=1
2021-09-14 03:17:32,804     DEBUG        client_log_config.py     Отладочная информация
2021-09-14 03:17:32,804     WARNING      client_log_config.py     Предупреждение!
2021-09-14 03:17:32,804     ERROR        client_log_config.py     Где-то ошибка!!
2021-09-14 03:17:32,804     CRITICAL     client_log_config.py     Где-то БОЛЬШАЯ ошибка!!!
2021-09-15 02:38:25,419     INFO         client_log_config.py     Важная? информация
2021-09-15 02:38:25,420     DEBUG        client_log_config.py     Houston, we have a %s, thorny problem, exc_info=1
2021-09-15 02:38:25,420     DEBUG        client_log_config.py     Отладочная информация
2021-09-15 02:38:25,420     WARNING      client_log_config.py     Предупреждение!
2021-09-15 02:38:25,420     ERROR        client_log_config.py     Где-то ошибка!!
2021-09-15 02:38:25,420     CRITICAL     client_log_config.py     Где-то БОЛЬШАЯ ошибка!!!
2021-09-16 16:12:54,856     INFO         client.py                fЗапущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777
2021-09-16 16:12:56,861     CRITICAL     client.py                Не удалось подключиться к серверу 127.0.0.1:7777, В подключении отказано.
2021-09-16 16:14:03,194     INFO         client.py                fЗапущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777
2021-09-16 16:14:03,198     DEBUG        client.py                Пользователь Guest теперь онлайн: отправил сообщение о(presence)
2021-09-16 16:14:03,200     DEBUG        client.py                Обработка сообщения от сервера: {'response': 200}
2021-09-16 16:14:03,200     INFO         client.py                Принят ответ от сервера 200 : OK
2021-09-16 16:14:15,128     INFO         client.py                fЗапущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777
2021-09-16 16:14:15,129     DEBUG        client.py                Пользователь Guest2 теперь онлайн: отправил сообщение о(presence)
2021-09-16 16:14:15,130     DEBUG        client.py                Обработка сообщения от сервера: {'response': 400, 'error': 'Bad Request'}
2021-09-16 16:14:15,130     INFO         client.py                Принят ответ от сервера 400 : Bad Request
2021-09-16 16:15:18,196     INFO         client.py                fЗапущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777
2021-09-16 16:15:18,197     DEBUG        client.py                Пользователь Guest теперь онлайн: отправил сообщение о(presence)
2021-09-16 16:15:18,204     ERROR        client.py                Не удалось декодировать сообщение сервера.
2021-09-16 16:48:47,162     INFO         client.py                fЗапущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777
2021-09-16 16:48:47,164     DEBUG        client.py                Пользователь Guest теперь онлайн: отправил сообщение о(presence)
2021-09-16 16:48:47,169     DEBUG        client.py                Обработка сообщения от сервера: {'response': 200}
2021-09-16 16:48:47,169     INFO         client.py                Принят ответ от сервера 200 : OK
2021-09-16 16:51:49,785     INFO         client.py                fЗапущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777
2021-09-16 16:51:49,787     DEBUG        client.py                Пользователь Guest теперь онлайн: отправил сообщение о(presence)
2021-09-16 16:51:49,788     DEBUG        client.py                Обработка сообщения от сервера: {'response': 400, 'error': 'Bad Request'}
2021-09-16 16:51:49,788     INFO         client.py                Принят ответ от сервера 400 : Bad Request
